name: TEST

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install docker
        uses: docker/setup-buildx-action@v2
      - name: build
        run: |
          make build
      - name: run
        run: |
          make github-actions-test
